ditto

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -33,11 +33,20 @@ jobs:
                 env:
                     PORT: 8080
                 run: |
-                    npm run start & (for attempt in {1..4}; do
+                    npm run start &
+                    for attempt in {1..20}; do
                         sleep 1
-                        if (curl --fail http://localhost:8080); then
-                            exit 0;
+                        if (curl http://localhost:8080 -f); then
+                            OK=1
+                            break
                         fi
                         echo "Waiting for server to start ($attempt/20)..."
-                    done) && exit 1
+                    done
+                    if [ $OK ]; then
+                        exit 0
+                    else
+                        echo "Failed to connect to server."
+                        exit 1
+                    fi
+                    kill -9 $(lsof -t -i:8080)
 
